<a href="https://colab.research.google.com/github/Sonypriyasonu/NLP_LAB/blob/main/NLPExperiment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment - 3

**Q.Write a program to implement the Minimum Edit Distance algorithm using Python.**


In [1]:
import numpy as np

def edit_Distance(X, Y):
    Xlen, Ylen = len(X), len(Y)
    table = np.zeros( (Xlen+1, Ylen+1), dtype=int)

    for i in range(1, Xlen+1):
        table[i, 0] = table[i-1, 0] + 1  # del cost - 1
    
    for j in range(1, Ylen+1):
        table[0, j] = table[0, j-1] + 1  #ins-cose - 1
    
    # Recurrence relation
    for i in range(1, Xlen+1):
        for j in range(1, Ylen+1):
            table[i, j] = min(
                table[i-1, j] + 1,
                table[i, j-1] + 1,
                table[i-1, j-1] if (X[i-1]==Y[j-1]) else table[i-1, j-1]+2
            )
    print(table)
    return table[Xlen, Ylen]


source = "text"
target = "test"
print(f'Distance between {source} and {target} is {edit_Distance(source, target)}')

[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 0 1 2]
 [3 2 1 2 3]
 [4 3 2 3 2]]
Distance between text and test is 2
